services:
  api:
    build: .
    ports:
      - "8080:8080"
  localstack:
    image: "localstack/localstack:3.6"
    environment:
      - SERVICES=dynamodb
    ports:
      - "4566:4566" # Localstack Gateway Port
      - "4510:4510" # DynamoDB Port